services:
  astrem:
    image: ghcr.io/robertaidenschofield/astrem-tv-main:latest
    build: https://github.com/RobertAidenSchofield/astrem-tv-main.git#main
    container_name: astrem
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000 # Internal container port


